---
title: "Range Shifts of the Black-capped Chickadee"
author: "Rory Macklin"
date: "`r Sys.Date()`"

geometry: margin=1in
header-includes:
  - \usepackage{setspace}
  - \doublespacing
  - \usepackage{lineno}
  - \linenumbers
  - \usepackage{fontspec}
  - \setmainfont{Times New Roman}
  
output: 
  pdf_document:
    latex_engine: xelatex


bibliography: Bibliography/Zotero_Library.bib

csl: Bibliography/ecology-letters.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Title**: Determining the Northern Extent of the Black-capped Chickadee (*Poecile atricapillus)* on the Sunshine Coast, British Columbia, Canada.

Rory Macklin^1\*^ , Jill Jankowski^1,2^

1.  University of British Columbia, Department of Zoology, Vancouver, British Columbia
2.  Biodiversity Research Centre, Vancouver, British Columbia

\*Corresponding Author

\newpage

# Abstract

Land conversion for human use has facilitated the expansion of a subset of species which are well adapted to urban environments. The Black-capped Chickadee (BCCH; *Poecile atricapillus*) is a wide-ranging North American parid known to be well adapted to urban and agricultural environments. In the Pacific Northwest, this species ranges throughout the Willamette Valley, surrounding lowlands, and coastal areas of northern California, Oregon, and Washington, USA. Community science efforts and published range maps place the northern coastal extent of the BCCH near Vancouver and the Howe Sound, British Columbia (BC), Canada. While some records exist along the more northerly Sunshine Coast of BC, data sparsity and under-sampling in this region lead to uncertainty in the northern extent of the BCCH in this region. To formally define this northern extent, we propose a systematic survey effort of the BCCH along a latitudinal gradient on the Sunshine Coast. We will establish a series of survey points along the Sunshine Coast from Gibson, BC, to the southern edge of Desolation Sound, BC, equally spaced across the area's range of latitude, ensuring to include points near human settlements such as Gibson and Powell River, BC. At these sites, we will roughly assess the habitat type and structure for inclusion as modeling covariates, and will employ a single-observer, distance-sampling and time-to-detection avian point-count methodology to allow for accounting of imperfect detection. Surveys will also be recorded for documentation of any auditory detections and verification to account for observer error. We will apply a hierarchical-modeling approach to estimate abundances of the BCCH at each site and produce an abundance gradient along increasing latitude. This method will allow us to assess the northern range extent of the BCCH in an under-surveyed region and determine to what extent human-settlements are facilitating BCCH presence. We find this insight to be of particular relevance as preliminary assessments suggest that BCCHs impose a strong suppressive effect on the region's Chestnut-backed Chickadee (CBCH; *Poecile rufescens*) populations, especially in urban habitats. Establishment of the BCCH on the Sunshine Coast could have ramifications for CBCH populations along the Coast and additionally on Vancouver Island, as the expansion past the northern edge of the Sunshine Coast would allow access to the Northern Gulf Islands, a possible route for BCCH crossover and establishment on Vancouver Island.

# Introduction

# Methods

# Results

# Discussion

# References
